import pandas as pd

data = [
    {"titulo": "Cien años de soledad", "autor": "Gabriel García Márquez", "año de publicación": 1967, "cantidad disponible": 10},
    {"titulo": "Don Quijote de la Mancha", "autor": "Miguel de Cervantes", "año de publicación": 1605, "cantidad disponible": 8},
    {"titulo": "Rayuela", "autor": "Julio Cortázar", "año de publicación": 1963, "cantidad disponible": 7},
    {"titulo": "Pedro Páramo", "autor": "Juan Rulfo", "año de publicación": 1955, "cantidad disponible": 5},
    {"titulo": "La sombra del viento", "autor": "Carlos Ruiz Zafón", "año de publicación": 2001, "cantidad disponible": 12},
    {"titulo": "El amor en los tiempos del cólera", "autor": "Gabriel García Márquez", "año de publicación": 1985, "cantidad disponible": 9},
    {"titulo": "Ficciones", "autor": "Jorge Luis Borges", "año de publicación": 1944, "cantidad disponible": 6},
    {"titulo": "La casa de los espíritus", "autor": "Isabel Allende", "año de publicación": 1982, "cantidad disponible": 11},
    {"titulo": "El túnel", "autor": "Ernesto Sabato", "año de publicación": 1948, "cantidad disponible": 4},
    {"titulo": "Sobre héroes y tumbas", "autor": "Ernesto Sabato", "año de publicación": 1961, "cantidad disponible": 3},
    {"titulo": "La ciudad y los perros", "autor": "Mario Vargas Llosa", "año de publicación": 1963, "cantidad disponible": 7},
    {"titulo": "Pantaleón y las visitadoras", "autor": "Mario Vargas Llosa", "año de publicación": 1973, "cantidad disponible": 6},
    {"titulo": "El Aleph", "autor": "Jorge Luis Borges", "año de publicación": 1949, "cantidad disponible": 5},
    {"titulo": "Los detectives salvajes", "autor": "Roberto Bolaño", "año de publicación": 1998, "cantidad disponible": 8},
    {"titulo": "2666", "autor": "Roberto Bolaño", "año de publicación": 2004, "cantidad disponible": 7},
    {"titulo": "La tregua", "autor": "Mario Benedetti", "año de publicación": 1960, "cantidad disponible": 10},
    {"titulo": "El coronel no tiene quien le escriba", "autor": "Gabriel García Márquez", "año de publicación": 1961, "cantidad disponible": 6},
    {"titulo": "Aura", "autor": "Carlos Fuentes", "año de publicación": 1962, "cantidad disponible": 9},
    {"titulo": "La muerte de Artemio Cruz", "autor": "Carlos Fuentes", "año de publicación": 1962, "cantidad disponible": 4},
    {"titulo": "Santa", "autor": "Federico Gamboa", "año de publicación": 1903, "cantidad disponible": 3},
    {"titulo": "El llano en llamas", "autor": "Juan Rulfo", "año de publicación": 1953, "cantidad disponible": 5},
    {"titulo": "La región más transparente", "autor": "Carlos Fuentes", "año de publicación": 1958, "cantidad disponible": 7},
    {"titulo": "La invención de Morel", "autor": "Adolfo Bioy Casares", "año de publicación": 1940, "cantidad disponible": 6},
    {"titulo": "El beso de la mujer araña", "autor": "Manuel Puig", "año de publicación": 1976, "cantidad disponible": 8},
    {"titulo": "La fiesta del chivo", "autor": "Mario Vargas Llosa", "año de publicación": 2000, "cantidad disponible": 9},
    {"titulo": "El entenado", "autor": "Juan José Saer", "año de publicación": 1983, "cantidad disponible": 4},
    {"titulo": "La guerra del fin del mundo", "autor": "Mario Vargas Llosa", "año de publicación": 1981, "cantidad disponible": 5},
    {"titulo": "El astillero", "autor": "Juan Carlos Onetti", "año de publicación": 1961, "cantidad disponible": 3},
    {"titulo": "El obsceno pájaro de la noche", "autor": "José Donoso", "año de publicación": 1970, "cantidad disponible": 2},
    {"titulo": "La casa verde", "autor": "Mario Vargas Llosa", "año de publicación": 1966, "cantidad disponible": 6},
    {"titulo": "El jardín de senderos que se bifurcan", "autor": "Jorge Luis Borges", "año de publicación": 1941, "cantidad disponible": 7},
    {"titulo": "La invención de Morel", "autor": "Adolfo Bioy Casares", "año de publicación": 1940, "cantidad disponible": 5},
    {"titulo": "El reino de este mundo", "autor": "Alejo Carpentier", "año de publicación": 1949, "cantidad disponible": 4},
    {"titulo": "El siglo de las luces", "autor": "Alejo Carpentier", "año de publicación": 1962, "cantidad disponible": 3},
    {"titulo": "La muerte y la brújula", "autor": "Jorge Luis Borges", "año de publicación": 1942, "cantidad disponible": 2},
    {"titulo": "El lugar sin límites", "autor": "José Donoso", "año de publicación": 1966, "cantidad disponible": 4},
    {"titulo": "La vida breve", "autor": "Juan Carlos Onetti", "año de publicación": 1950, "cantidad disponible": 5},
    {"titulo": "El perseguidor", "autor": "Julio Cortázar", "año de publicación": 1959, "cantidad disponible": 6},
    {"titulo": "Bestiario", "autor": "Julio Cortázar", "año de publicación": 1951, "cantidad disponible": 7},
    {"titulo": "La casa de Adela", "autor": "Guillermo Fadanelli", "año de publicación": 2016, "cantidad disponible": 8},
]

df = pd.DataFrame(data)
df.to_excel("libros.xlsx", index=False)