# Generated by Django 5.2.1 on 2025-05-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year_publication',
            field=models.CharField(max_length=4),
        ),
    ]
